name: '[MyApp] Demo Team Deployment'

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: true
  - name: prerelease
    displayName: Publish prerelease module
    type: boolean
    default: false
  - name: versionOption
    displayName: Version option for module
    type: string
    default: patch
    values:
      - major
      - minor
      - patch

pr:
  branches:
    include:
    - features/*
    - main
  paths:
    include:
      - '/Solutions/MyApp/variables/demo.tfvars'
      - '/.azuredevops/solutionPipelines/myApp.demo.yml'
      - '/.azuredevops/pipelineTemplates/*.yml'
      - '/Solutions/MyApp/*.tf'
    exclude:
      - '/**/*.md'

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/Solutions/MyApp/variables/demo.tfvars'
      - '/.azuredevops/solutionPipelines/myApp.demo.yml'
      - '/.azuredevops/pipelineTemplates/*.yml'
      - '/Solutions/MyApp/*.tf'
    exclude:
      - '/**/*.md'

variables:
  - name: serviceName
    value: 'myapp.demo'
  - name: modulePath
    value: '$(System.DefaultWorkingDirectory)/Solutions/MyApp/'
  - name: planName
    value: $(serviceName)_$(Build.BuildId).tfplan
  - name: tfvarsPath
    value: 'variables/demo.tfvars'
  - template: '../../settings.yml'

pool:
  name: $(poolName)
  demands:
    - Agent.OS -equals Linux

stages:
  - template: /.azuredevops/pipelineTemplates/stages.module.yml
    parameters:
      removeDeployment: '${{ parameters.removeDeployment }}'
      prerelease: '${{ parameters.prerelease }}'
      versionOption: '${{ parameters.versionOption }}'
